import {
  ENV_BASE_LOCATION,
  ENV_MAX_RADIUS_KM,
  ENV_COMMISSION_RATE_DEFAULT,
  ENV_SUBSCRIPTION_MONTHLY_RDP,
  ENV_TRIAL_DAYS,
  ENV_GRACE_DAYS,
  ENV_REFERRALS_ENABLED,
  ENV_REFERRAL_NEW_CUSTOMER_BONUS_RDP,
  ENV_REFERRAL_REFERRER_BONUS_RDP,
  ENV_PROMO_MAX_PERCENT,
  ENV_PROMO_MAX_FIXED_RDP,
  ENV_PROMO_CODE_MAX_LEN,
  ENV_SUPPORT_WHATSAPP_E164,
  ENV_SUPPORT_WHATSAPP_DEFAULT_TEXT,
  ENV_DEV_ALLOW_ORDER_LOCATION_BYPASS,
} from "@/lib/env";

export const BASE_LOCATION = {
  // TODO: replace with exact Google Maps coordinates for your HQ.
  lat: ENV_BASE_LOCATION.lat,
  lng: ENV_BASE_LOCATION.lng,
};

export const MAX_RADIUS_KM = ENV_MAX_RADIUS_KM;
export const COMMISSION_RATE_DEFAULT = ENV_COMMISSION_RATE_DEFAULT;
export const SUBSCRIPTION_MONTHLY_RDP = ENV_SUBSCRIPTION_MONTHLY_RDP;
export const TRIAL_DAYS = ENV_TRIAL_DAYS;
export const GRACE_DAYS = ENV_GRACE_DAYS;
export const REFERRALS_ENABLED = ENV_REFERRALS_ENABLED;
export const REFERRAL_NEW_CUSTOMER_BONUS_RDP = ENV_REFERRAL_NEW_CUSTOMER_BONUS_RDP;
export const REFERRAL_REFERRER_BONUS_RDP = ENV_REFERRAL_REFERRER_BONUS_RDP;
export const PROMO_MAX_PERCENT = ENV_PROMO_MAX_PERCENT;
export const PROMO_MAX_FIXED_RDP = ENV_PROMO_MAX_FIXED_RDP;
export const PROMO_CODE_MAX_LEN = ENV_PROMO_CODE_MAX_LEN;
export const SUPPORT_WHATSAPP_E164 = ENV_SUPPORT_WHATSAPP_E164;
export const SUPPORT_WHATSAPP_DEFAULT_TEXT = ENV_SUPPORT_WHATSAPP_DEFAULT_TEXT;
export const SUPPORT_WHATSAPP_LINK_BASE = `https://wa.me/${SUPPORT_WHATSAPP_E164}?text=`;
export const DEV_ALLOW_ORDER_LOCATION_BYPASS = ENV_DEV_ALLOW_ORDER_LOCATION_BYPASS;
